/* Throw*/

try {
    throw new Error ();

} catch(err) {
    console.log(err)
}
console.log('This line now runs');